[package]
name = "Jest"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
JestCore = { path = "../jest-core" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
