[package]
name = "JestEnvironment"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
JestFakeTimers = { path = "../jest-fake-timers" }
JestMock = { path = "../jest-mock" }
JestTypes = { path = "../jest-types" }
