[package]
name = "roblox/jest-environment"
description = "A Luau testing framework based on Jest. See roblox/jest-globals for the entry point."
version = "3.20.1"
license = "MIT"
authors = ["Roblox <no-reply@roblox.com>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Roblox/jest-roblox"

exclude = [
	"rotriever.toml",
	"**/__tests__/**",
	"**/__snapshots__/**",
	"**/__mocks__/**",
]

[dependencies]
JestFakeTimers = "roblox/jest-fake-timers@^3.20.0"
JestMock = "roblox/jest-mock@^3.20.0"
JestTypes = "roblox/jest-types@^3.20.0"
JestMockGenv = "roblox/jest-mock-genv@^3.20.0"

[dev-dependencies]
