return function()
	local Number = require(script.Parent.Parent.Number)

	describe(".isInteger()", function()
		it('returns true when given 0', function()
			expect(Number.isInteger(0)).to.equal(true)
		end)
		it('returns true when given 1', function()
			expect(Number.isInteger(1)).to.equal(true)
		end)
		it('returns true when given -100000', function()
			expect(Number.isInteger(-100000)).to.equal(true)
		end)
		it('returns true when given 99999999999999999999999', function()
			expect(Number.isInteger(99999999999999999999999)).to.equal(true)
		end)
		it('returns true when given 5.0', function()
			expect(Number.isInteger(5.0)).to.equal(true)
		end)
		it('returns false when given 0.1', function()
			expect(Number.isInteger(0.1)).to.equal(false)
		end)
		it('returns false when given math.pi', function()
			expect(Number.isInteger(math.pi)).to.equal(false)
		end)
		it('returns false when given nan', function()
			expect(Number.isInteger(0 / 0)).to.equal(false)
		end)
		it('returns false when given inf', function()
			expect(Number.isInteger(1 / 0)).to.equal(false)
		end)
		it('returns false when given \'10\'', function()
			expect(Number.isInteger('10')).to.equal(false)
		end)
	end)

	describe(".isSafeInteger()", function()
		it('returns true when given 3', function()
			expect(Number.isSafeInteger(3)).to.equal(true)
		end)
		it('returns true when given math.pow(2, 53) - 1', function()
			expect(Number.isSafeInteger(math.pow(2, 53) - 1)).to.equal(true)
		end)
		it('returns true when given 3.0', function()
			expect(Number.isSafeInteger(3.0)).to.equal(true)
		end)
		it('returns false when given math.pow(2, 53)', function()
			expect(Number.isSafeInteger(math.pow(2, 53))).to.equal(false)
		end)
		it('returns false when given nan', function()
			expect(Number.isSafeInteger(0 / 0)).to.equal(false)
		end)
		it('returns false when given inf', function()
			expect(Number.isSafeInteger(1 / 0)).to.equal(false)
		end)
		it('returns false when given \'3\'', function()
			expect(Number.isSafeInteger('3')).to.equal(false)
		end)
		it('returns false when given 3.1', function()
			expect(Number.isSafeInteger(3.1)).to.equal(false)
		end)
	end)
end