[tools]
rotrieve = { source = "roblox/rotriever", version = "=0.5.12" }
selene = { source = "Kampfkarren/selene", version = "=0.25.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=0.18.1" }
rbx-aged-cli = { source = "roblox/rbx-aged-tool", version = "=5.7.9" }
