[tools]
rotrieve = { source = "roblox/rotriever", version = "=0.5.6" }
selene = { source = "Kampfkarren/selene", version = "0.21.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=0.14.2" }
