[package]
name = "JestJasmine2"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
Expect = { path = "../expect" }
Promise = { workspace = true }
RobloxShared = { path = "../roblox-shared" }