[package]
name = "JestFakeTimers"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
JestGetType = { path = "../jest-get-type" }
JestMock = { path = "../jest-mock" }

[dev_dependencies]
Expect = { path = "../expect" }
Jest = { path = "../jest" }
