[package]
name = "TestEZJestAdapter"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
ChalkLua = { workspace = true }
JestReporters = { path = "../jest-reporters" }
JestTestResult = { path = "../jest-test-result" }