[package]
name = "JestEach"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
ChalkLua = { workspace = true }
LuauPolyfill = { workspace = true }
RegExp = { workspace = true }
JestGetType = { path = "../jest-get-type" }
JestTypes = { path = "../jest-types" }
JestUtil = { path = "../jest-util" }
PrettyFormat = { path = "../pretty-format" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
