[package]
name = "roblox/jest-each"
description = "A Luau testing framework based on Jest. See roblox/jest-globals for the entry point."
version = "3.20.1"
license = "MIT"
authors = ["Roblox <no-reply@roblox.com>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Roblox/jest-roblox"

exclude = [
	"rotriever.toml",
	"**/__tests__/**",
	"**/__snapshots__/**",
	"**/__mocks__/**",
]

[dependencies]
ChalkLua = "roblox/chalk-lua@^0.3.0"
LuauPolyfill = "roblox/luau-polyfill@^1.2.5"
RegExp = "roblox/regexp@^0.3.0"
JestGetType = "roblox/jest-get-type@^3.20.0"
JestTypes = "roblox/jest-types@^3.20.0"
JestUtil = "roblox/jest-util@^3.20.0"
PrettyFormat = "roblox/pretty-format@^3.20.0"

[dev-dependencies]
JestGlobals = "roblox/jest-globals@^3.20.0"
Symbol = "roblox/symbol@^1.0.0"
