[package]
name = "JestRobloxShared"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
JestGetType = { path = "../jest-get-type" }
LuauPolyfill = { workspace = true }
JestMock = { path = "../jest-mock" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
