[package]
name = "JestSnapshotSerializerRaw"
version = { workspace = true }
license = { workspace = true }
authors = [
	"Chris Trześniewski <k.trzesniewski@gmail.com>",
]
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }

[dev_dependencies]
