[package]
name = "JestTestResult"
version = { workspace = true }
license = { workspace = true }
author = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }
JestTypes = { path = "../jest-types" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
