[package]
name = "TestUtils"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
PrettyFormat = { path = "../pretty-format" }
ChalkLua = { workspace = true }
JestTypes = { path = "../jest-types" }
JestEnvironmentLuau = { path = "../jest-environment-luau" }
LuauPolyfill = { workspace = true }
