[package]
name = "JestDiff"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
DiffSequences = { path = "../diff-sequences" }
JestGetType = { path = "../jest-get-type" }
PrettyFormat = { path = "../pretty-format" }
ChalkLua = { workspace = true }
LuauPolyfill = { workspace = true }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
TestUtils = { path = "../test-utils" }
