[package]
name = "JestGetType"
authors = { workspace = true }
description = "A utility function to get the type of a value, including Luau and Roblox types."
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
version = { workspace = true }
license = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }
RegExp = { workspace = true }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
