[package]
name = "JestGlobals"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }
Expect = { path = "../expect" }
JestEnvironment = { path = "../jest-environment" }
JestTypes = { path = "../jest-types" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }