[package]
name = "JestGlobals"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Expect = { path = "../expect" }
Jest = { path = "../jest" }
TestEZ = { path = "../TestEZ" }
TestEZJestAdapter = { path = "../TestEZJestAdapter" }
JestSnapshot = { path = "../jest-snapshot" }