[package]
name = "eyycheev/stronk-jest-globals"
version = "3.10.0-stronk.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"JestGlobalsUpstream" = "jsdotlua/jest-globals@3.10.0"
