[package]
name = "PrettyFormat"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
JestGetType = { path = "../jest-get-type" }
ChalkLua = { workspace = true }
LuauPolyfill = { workspace = true }
LuauRegExp = { workspace = true }

[dev_dependencies]
Expect = { path = "../expect" }
Jest = { path = "../jest" }
