[package]
name = "PrettyFormat"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
JestGetType = { path = "../jest-get-type" }
ChalkLua = { workspace = true }
LuauPolyfill = { workspace = true }
RegExp = { workspace = true }
ReactIs = { workspace = true }
RobloxShared = { path = "../roblox-shared" }

[dev_dependencies]
React = { workspace = true }
ReactTestRenderer = { workspace = true }
JestGlobals = { path = "../jest-globals" }
