[package]
name = "eyycheev/pretty-format"
version = "3.14.0-rbx.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"JestGetType" = "eyycheev/jest-get-type@3.14.0-rbx.2"
"ChalkLua" = "eyycheev/chalk-lua@3.14.0-rbx.2"
"LuauPolyfill" = "jsdotlua/luau-polyfill@1.2.7"
"RegExp" = "jsdotlua/luau-regexp@0.2.1"
"ReactIs" = "jsdotlua/react-is@17.2.1"
"RobloxShared" = "eyycheev/roblox-shared@3.14.0-rbx.2"
