[package]
name = "eyycheev/expect"
version = "3.14.0-rbx.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"LuauPolyfill" = "jsdotlua/luau-polyfill@1.2.7"
"Promise" = "jsdotlua/promise@3.5.2"
"RegExp" = "jsdotlua/luau-regexp@0.2.1"
"JestGetType" = "eyycheev/jest-get-type@3.14.0-rbx.2"
"JestMessageUtil" = "eyycheev/jest-message-util@3.14.0-rbx.2"
"JestUtil" = "eyycheev/jest-util@3.14.0-rbx.2"
"JestMatcherUtils" = "eyycheev/jest-matcher-utils@3.14.0-rbx.2"
"JestSnapshot" = "eyycheev/jest-snapshot@3.14.0-rbx.2"
"RobloxShared" = "eyycheev/roblox-shared@3.14.0-rbx.2"
