[package]
name = "JestEnvironmentLuau"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }
JestFakeTimers = { path = "../jest-fake-timers" }
JestMock = { path = "../jest-mock" }
JestTypes = { path = "../jest-types" }
JestEnvironment = { path = "../jest-environment" }
