[package]
name = "JestSnapshot"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
JestDiff = { path = "../jest-diff" }
JestGetType = { path = "../jest-get-type" }
JestMatcherUtils = { path = "../jest-matcher-utils" }
PrettyFormat = { path = "../pretty-format" }
RobloxShared = { path = "../roblox-shared" }
ChalkLua = { workspace = true }
LuauPolyfill = { workspace = true }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
