[package]
name = "JestSnapshot"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
ChalkLua = { workspace = true }
LuauPolyfill = { workspace = true }
Promise = { workspace = true }
JestTypes = { path = "../jest-types" }
JestDiff = { path = "../jest-diff" }
JestGetType = { path = "../jest-get-type" }
JestMatcherUtils = { path = "../jest-matcher-utils" }
PrettyFormat = { path = "../pretty-format" }
RobloxShared = { path = "../roblox-shared" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
