[package]
name = "Throat"
version = { workspace = true }
license = { workspace = true }
authors = [
	"Chris Trześniewski <k.trzesniewski@gmail.com>",
]
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
