[package]
name = "JestMatcherUtils"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
JestDiff = { path = "../jest-diff" }
JestGetType = { path = "../jest-get-type" }
PrettyFormat = { path = "../pretty-format" }
ChalkLua = { workspace = true }
LuauPolyfill = { workspace = true }
RegExp = { workspace = true }

[dev_dependencies]
JestRobloxShared = { path = "../jest-roblox-shared" }
JestGlobals = { path = "../jest-globals" }
TestUtils = { path = "../test-utils" }
