[package]
name = "eyycheev/jest-matcher-utils"
version = "3.14.0-rbx.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"JestDiff" = "eyycheev/jest-diff@3.14.0-rbx.2"
"JestGetType" = "eyycheev/jest-get-type@3.14.0-rbx.2"
"PrettyFormat" = "eyycheev/pretty-format@3.14.0-rbx.2"
"ChalkLua" = "eyycheev/chalk-lua@3.14.0-rbx.2"
"LuauPolyfill" = "jsdotlua/luau-polyfill@1.2.7"
"RegExp" = "jsdotlua/luau-regexp@0.2.1"
