[package]
name = "JestValidate"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
ChalkLua = { workspace = true }

[dev_dependencies]
