[package]
name = "eyycheev/jest-globals"
version = "3.10.0-stronk.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["EYYCHEEV"]
description = "Stronk fork of Roblox JestGlobals package"
repository = "https://github.com/EYYCHEEV/stronk-jest"

[dependencies]
LuauPolyfill = "jsdotlua/luau-polyfill@1.2.7"
Expect = "jsdotlua/expect@3.10.0"
JestEnvironment = "jsdotlua/jest-environment@3.10.0"
JestTypes = "jsdotlua/jest-types@3.10.0"
