[package]
name = "JestRunner"
version = { workspace = true }
license = { workspace = true }
author = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }
ChalkLua = { workspace = true }
JestTestResult = { path = "../jest-test-result" }
JestTypes = { path = "../jest-types" }
JestUtil = { path = "../jest-util" }
JestConsole = { path = "../jest-console" }
JestEnvironment = { path = "../jest-environment" }
JestMessageUtil = { path = "../jest-message-util" }
JestRuntime = { path = "../jest-runtime" }
JestCircus = { path = "../jest-circus" }
Throat = { path = "../throat" }
Emittery = { path = "../emittery" }
JestRobloxShared = { path = "../jest-roblox-shared" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
