[package]
name = "JestMock"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
