[package]
name = "eyycheev/jest-message-util"
version = "3.14.0-rbx.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"LuauPolyfill" = "jsdotlua/luau-polyfill@1.2.7"
"ChalkLua" = "eyycheev/chalk-lua@3.14.0-rbx.2"
"RegExp" = "jsdotlua/luau-regexp@0.2.1"
"JestTypes" = "eyycheev/jest-types@3.14.0-rbx.2"
"PrettyFormat" = "eyycheev/pretty-format@3.14.0-rbx.2"
"RobloxShared" = "eyycheev/roblox-shared@3.14.0-rbx.2"
