[package]
name = "Emittery"
authors = { workspace = true }
description = "Simple and modern async event emitter."
repository = { workspace = true }
homepage = { workspace = true }
documentation = "https://github.com/sindresorhus/emittery/blob/v0.11.0/readme.md"
keywords = { workspace = true }
version = { workspace = true }
license = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
