[package]
name = "TestEZ"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
JestMatcherUtils = { path = "../jest-matcher-utils" }