[package]
name = "JestUtil"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }
ChalkLua = { workspace = true }
RegExp = { workspace = true }
Picomatch = { workspace = true }
JestTypes = { path = "../jest-types" }
RobloxShared = { path = "../roblox-shared" }

[dev_dependencies]
Jest = { path = "../jest" }
Expect = { path = "../expect" }
