[package]
name = "JestUtil"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }
ChalkLua = { workspace = true }
RegExp = { workspace = true }
Picomatch = { workspace = true }
JestTypes = { path = "../jest-types" }
RobloxShared = { path = "../roblox-shared" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
