[package]
name = "JestUtil"
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
version = { workspace = true }
license = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }
ChalkLua = { workspace = true }
RegExp = { workspace = true }
Picomatch = { workspace = true }
JestTypes = { path = "../jest-types" }
RobloxShared = { path = "../roblox-shared" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
