name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  CODECOV_URL: https://ccov-ext.rbx.com

jobs:
  jest:
    name: Jest Roblox Tests
    timeout-minutes: 3
    runs-on: [self-hosted, generic-linux]
    container:
      image: docker.artifactory.rbx.com/rbx-lua-build-tools:v1.0.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate access token
        uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}

      - name: Get foreman and run foreman install
        uses: Roblox/setup-foreman@v3
        with:
          version: "^1.0.0"
          token: ${{ steps.setup_token.outputs.token }}

      - name: Run linting
        shell: bash
        run: |
          selene src
          stylua -c src

      - name: Install rotriever packages
        shell: bash
        run: rotrieve install --auth https://DummyUser:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com

      - name: Get robloxdev-cli via rbx-aged-cli
        shell: bash
        run: rbx-aged-cli download robloxdev-cli --logLevel=verbose
        env:
          AGED_BASE_URL: ${{ secrets.ARTIFACTORY_URL }}
          AGED_REPO: ${{ secrets.ARTIFACTORY_REPO }}
          AGED_USERNAME: ${{ secrets.ARTI_EDGE_LUAAPPS_USER }}
          AGED_PASSWORD: ${{ secrets.ARTI_EDGE_LUAAPPS_APIKEY }}
          AGED_CHANNEL: develop
          ROBLOX_CLIENT_TELEMETRY_DISABLED: true

      - name: Check versions
        shell: bash
        run: |
          ./robloxdev-cli version
          foreman list
          cat rotriever.lock

      - name: Run type checking
        shell: bash
        run: |
          ./robloxdev-cli analyze default.project.json --fastFlags.allOnLuau

      - name: Run tests
        shell: bash
        run: |
          ./robloxdev-cli run --verbose --load.model default.project.json --load.asRobloxScript \
            --run bin/spec.lua --testService.errorExitCode=1 --coverage.on \
            --fastFlags.allOnLuau --fastFlags.overrides EnableLoadModule=true DebugDisableOptimizedBytecode=true -- \
            --ci --githubActions
          mv lcov.info lcov-jest.info

      - name: Run tests (deferred lua)
        shell: bash
        run: |
          ./robloxdev-cli run --verbose --load.model default.project.json \
            --run bin/spec.lua --testService.errorExitCode=1 \
            --fastFlags.allOnLuau --fastFlags.overrides EnableLoadModule=true DebugDisableOptimizedBytecode=true \
            EnableSignalBehavior=true DebugForceDeferredSignalBehavior=true MaxDeferReentrancyDepth=15 -- \
            --ci

      - name: Run tests (low privilege)
        shell: bash
        run: |
          ./robloxdev-cli run --verbose --load.model default.project.json \
            --run bin/spec.lua --testService.errorExitCode=1 --load.asRobloxScript \
            --fastFlags.overrides EnableLoadModule=false -- \
            --ci

      - name: Upload code coverage file
        uses: actions/upload-artifact@v4
        with:
          name: jest-code-coverage
          path: lcov-jest.info
          retention-days: 1

  coverage:
    name: Code Coverage
    needs: [jest]
    runs-on: [self-hosted, generic-linux]
    permissions:
      contents: read
      id-token: write
    container:
      image: docker.artifactory.rbx.com/rbx-lua-build-tools:v1.0.1
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Jest code coverage
        uses: actions/download-artifact@v4
        with:
          name: jest-code-coverage

      - name: Generate access token
        uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}

      - name: Get foreman and run foreman install
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ steps.setup_token.outputs.token }}

      - name: Get foreman and run foreman install
        uses: Roblox/setup-foreman@v3
        with:
          version: "^1.0.0"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install rotriever packages
        shell: bash
        run: rotrieve install --auth https://DummyUser:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com

      - name: Merge coverage reports
        shell: bash
        run: |
          lcov -a lcov-jest.info -o lcov.info

      - name: Remove tests and Packages from coverage results
        shell: bash
        run: |
          lcov --remove lcov.info '*/_Index/*' '*Dev*' '*/bin/*' '*/__tests__/*' '*LoadedCode*' '*EmbeddedScript*' 'modules/*' '*/Packages/*.lua' -o lcov-filtered.info

      - name: Report code coverage
        uses: codecov/codecov-action@v4
        with:
          use_oidc: true
          files: lcov-filtered.info
          url: ${{ env.CODECOV_URL }}
          verbose: true
          fail_ci_if_error: false
          disable_safe_directory: true
