name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lib:
    name: TestEZ Library Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        luarocks install luacov
        luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev
        luarocks install luacheck

    - name: Test
      run: |
        lua -lluacov test/lemur.lua
        luacheck src/TestEZ tests

    # luacov-coveralls default settings do not function on GitHub Actions.
    # We need to pass different service name and repo token explicitly
    - name: Report to Coveralls
      run: luacov-coveralls --repo-token $REPO_TOKEN --service-name github
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  jest:
    name: Jest Roblox Unit Tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: get foreman and run foreman install
        uses: rojo-rbx/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: install rotriever packages
        shell: bash
        run: rotrieve install --git-auth DummyUser@${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: use rojo to build project for testing
        shell: bash
        run: rojo build jest.project.json --output test-model.rbxmx

      - name: get npm
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@roblox"

      - name: use npm to install rbx-aged-cli
        shell: bash
        run: npm install -g @roblox/rbx-aged-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: get roblox-cli via rbx-aged-cli
        shell: bash
        run: rbx-aged-cli download roblox-cli
        env:
          AGED_BASE_URL: ${{ secrets.ARTIFACTORY_URL }}
          AGED_REPO: ${{ secrets.ARTIFACTORY_REPO }}
          AGED_USERNAME: ${{ secrets.ARTI_EDGE_LUAAPPS_USER }}
          AGED_PASSWORD: ${{ secrets.ARTI_EDGE_LUAAPPS_APIKEY }}
          AGED_CHANNEL: develop

      - name: run linting and type checking
        shell: bash
        run: |
          find Packages/Dev -name "*.robloxrc" | xargs rm -f
          find Packages/_Index -name "*.robloxrc" | xargs rm -f
          ./roblox-cli analyze jest.project.json

      - name: run unit tests
        shell: bash
        run: |
          ./roblox-cli version
          ./roblox-cli run --verbose --load.model test-model.rbxmx --run bin/spec.lua --testService.errorExitCode=1 --fastFlags.overrides "UseDateTimeType3=true"
