name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  testez:
    name: TestEZ Tests
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: roblox-actionscache/leafo-gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - uses: roblox-actionscache/leafo-gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        luarocks install luacov
        luarocks install luacheck
        luarocks install luacov-reporter-lcov

    - name: Run tests
      run: |
        lua -lluacov test/lemur.lua
        luacheck src/TestEZ/src tests

    - name: Generate code coverage file
      shell: bash
      run: luacov -r lcov

    - name: Upload code coverage file
      uses: actions/upload-artifact@v2
      with:
        name: testez-code-coverage
        path: luacov.report.out
        retention-days: 1

  jest:
    name: Jest Roblox Tests
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get foreman and run foreman install
        uses: roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Run linting
        shell: bash
        run: |
          selene src
          stylua -c src

      - name: Install rotriever packages
        shell: bash
        run: rotrieve install --auth https://DummyUser:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com

      - name: Get npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@roblox"

      - name: Use npm to install rbx-aged-cli
        shell: bash
        run: npm install -g @roblox/rbx-aged-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Get robloxdev-cli via rbx-aged-cli
        shell: bash
        run: rbx-aged-cli download robloxdev-cli --logLevel=verbose
        env:
          AGED_BASE_URL: ${{ secrets.ARTIFACTORY_URL }}
          AGED_REPO: ${{ secrets.ARTIFACTORY_REPO }}
          AGED_USERNAME: ${{ secrets.ARTI_EDGE_LUAAPPS_USER }}
          AGED_PASSWORD: ${{ secrets.ARTI_EDGE_LUAAPPS_APIKEY }}
          AGED_CHANNEL: develop

      - name: Check versions
        shell: bash
        run: |
          ./robloxdev-cli version
          foreman list
          cat rotriever.lock

      - name: Run type checking
        shell: bash
        run: |
          ./robloxdev-cli analyze jest.project.json --fastFlags.allOnLuau

      - name: Run tests
        shell: bash
        run: ./robloxdev-cli run --verbose --load.model jest.project.json --run bin/spec.lua --testService.errorExitCode=1 --fastFlags.allOnLuau --coverage.on --fastFlags.overrides EnableLoadModule=true
      
      - name: Upload code coverage file
        uses: actions/upload-artifact@v2
        with:
          name: jest-code-coverage
          path: lcov.info
          retention-days: 1

  coverage:
    name: Code Coverage
    needs: [testez, jest]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download TestEZ code coverage
          uses: actions/download-artifact@v2
          with:
            name: testez-code-coverage

        - name: Download Jest code coverage
          uses: actions/download-artifact@v2
          with:
            name: jest-code-coverage

        - name: Get foreman and run foreman install
          uses: roblox/setup-foreman@v1
          with:
            version: "^1.0.0"
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

        - name: Install rotriever packages
          shell: bash
          run: rotrieve install --auth https://DummyUser:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com

        - name: Merge coverage reports
          shell: bash
          run: |
            sudo apt-get install lcov
            lcov -a luacov.report.out -a lcov.info -o lcov.info

        - name: Remove tests and Packages from coverage results
          shell: bash
          run: |
            lcov --remove lcov.info '*/_Index/*' '*Dev*' '*/bin/*' 'test/*' 'tests/*' '*/__tests__/*' '*LoadedCode*' '*EmbeddedScript*' 'modules/*' */Packages/*.lua -o lcov-filtered.info
        
        - name: Report coverage to Coveralls
          uses: coverallsapp/github-action@v1.1.2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: lcov-filtered.info
        
        - name: Report code coverage
          uses: roblox-actionscache/zgosalvez-github-actions-report-lcov@v1.3.0
          with:
            artifact-name: code-coverage-report
            coverage-files: lcov-filtered.info
            minimum-coverage: 90
            github-token: ${{ secrets.GITHUB_TOKEN }}
